name: Gradle Publish

on:
  release:
    types: [ created ]
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle publish
        env:
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGNING_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.SIGNING_KEY_PUBLIC }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
        run: ./gradlew jreleaserConfig clean publish jreleaserDeploy
